CREATE TRIGGER tr_Delete_User ON Users INSTEAD OF DELETE 
AS
UPDATE USERS 
SET CredentialId = NULL
WHERE CredentialId IN (SELECT CredentialId FROM DELETED)

DELETE FROM Credentials
WHERE Id IN (SELECT CredentialId FROM DELETED)

DELETE FROM UsersChats
WHERE UserId IN (SELECT Id FROM DELETED)

UPDATE Messages
SET UserId = NULL
WHERE UserId IN (SELECT Id FROM DELETED)

DELETE FROM Users
WHERE Id IN (SELECT Id FROM DELETED)